### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by zqlsnr** [youdilab/cnn-chorus-detection#1]
Hello, do you have any examples of training data, and are there any dependency files for the running TensorFlow and Keras versions?

**Comment by youdilab** [comment]
Hi, regarding examples of training data, please check;
[01_1_DataGenerationResults](https://github.com/youdilab/cnn-chorus-detection/tree/main/01_1_DataGenerationResults)

(I just uploaded it today after your comment and thank you for bringing it up.)

It contains the metadata.csv file for the entire dataset plus the an example dataset of 82 wav files (which happen to be the first 82 files generated in the dataset).

**Comment by youdilab** [comment]
Hi, regarding the dependency files;

-I have added usedVersions.txt file now which contains versions by the last time this was run.
tensorflow==2.11.0
keras==2.11.0

If you run into any issues, please do let me know, would be happy to help.

**Comment by youdilab** [comment]
Next Step: Upload requirements.txt file including all libraries.

**Comment by zqlsnr** [comment]
Thank you for your response. Thanks a lot!
